var btn1 = document.getElementById("btn-1");
var btn2 = document.getElementById("btn-2");
var btn3 = document.getElementById("btn-3");
var btn4 = document.getElementById("btn-4");
var pages = document.getElementById("pages");
btn1.addEventListener("click", () => {
  document.getElementById("page-1").style.display = "none";
  document.getElementById("page-2").style.display = "block";
  document.getElementById("page-3").style.display = "none";
  document.getElementById("page-4").style.display = "none";
  document.getElementById("page-5").style.display = "none";
  btn1.style.backgroundColor = "#eee7e7";
  btn2.style.backgroundColor = "white";
  btn3.style.backgroundColor = "white";
  btn4.style.backgroundColor = "white";
});
btn2.addEventListener("click", () => {
  document.getElementById("page-1").style.display = "none";
  document.getElementById("page-2").style.display = "none";
  document.getElementById("page-3").style.display = "block";
  document.getElementById("page-4").style.display = "none";
  document.getElementById("page-5").style.display = "none";
  btn1.style.backgroundColor = "white";
  btn2.style.backgroundColor = "#eee7e7";
  btn3.style.backgroundColor = "white";
  btn4.style.backgroundColor = "white";
});
btn3.addEventListener("click", () => {
  document.getElementById("page-1").style.display = "none";
  document.getElementById("page-2").style.display = "none";
  document.getElementById("page-3").style.display = "none";
  document.getElementById("page-4").style.display = "block";
  document.getElementById("page-5").style.display = "none";
  btn1.style.backgroundColor = "white";
  btn2.style.backgroundColor = "white";
  btn3.style.backgroundColor = "#eee7e7";
  btn4.style.backgroundColor = "white";
});
btn4.addEventListener("click", () => {
  document.getElementById("page-1").style.display = "none";
  document.getElementById("page-2").style.display = "none";
  document.getElementById("page-3").style.display = "none";
  document.getElementById("page-4").style.display = "none";
  document.getElementById("page-5").style.display = "block";
  btn1.style.backgroundColor = "white";
  btn2.style.backgroundColor = "white";
  btn3.style.backgroundColor = "white";
  btn4.style.backgroundColor = "#eee7e7";
});
